[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-set-user-default",
    "allow-get-user-default",
    "allow-save-keychain",
    "allow-load-keychain",
    "allow-set-theme",
    "allow-show-hud",
    "allow-close-hud"
]
